apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.infra.example.com
spec:
  group: infra.example.com
  names: { kind: Database, plural: databases, shortNames: ["db"] }
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                engine: { type: string, enum: ["mysql", "postgres"] }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backends.infra.example.com
spec:
  group: infra.example.com
  names: { kind: Backend, plural: backends, shortNames: ["be"] }
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image: { type: string }
                connectToDatabase: { type: string } # <--- The Link!
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontends.infra.example.com
spec:
  group: infra.example.com
  names: { kind: Frontend, plural: frontends, shortNames: ["fe"] }
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image: { type: string }
                connectToBackend: { type: string } # <--- The Link!