apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosmonkeys.ops.example.com
spec:
  group: ops.example.com
  names:
    kind: ChaosMonkey
    plural: chaosmonkeys
    shortNames: ["chaos"]
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                target_app_label:
                  type: string